#!/bin/bash


RES_DIR=$PWD/../resource/ # beware! '/' at the end is required!
BUILD_DIR=$PWD/../bin/
task=$1
req=100
batch=1
mean=100
res=20
output="$task"_"$res"

#for i in {1,2,4,8,16,32}
#do

SERVER_PID=$(echo get_server_list | nvidia-cuda-mps-control)
echo set_active_thread_percentage $SERVER_PID $res | nvidia-cuda-mps-control

rm ./data/"$output".ncu-rep

if true
then
#nsys profile -t cuda -s none --export=sqlite --force-overwrite=true -o data/"$task"_"$batch"\
ncu -o "$task".ncu-rep --metrics \
    gpu__time_duration.sum,lts__t_sectors.avg.pct_of_peak_sustained_elapsed \
    $BUILD_DIR/standalone_inference --task $task --taskfile $RES_DIR/models/$task.pt --requests $req \
    --batch $batch --mean $mean --input $RES_DIR/$input_tx --input_config_json $RES_DIR/input_config.json\
    
fi


ncu --import data/"$output".ncu-rep --csv > data/"$output".csv

python3 l2cache.py data/"$output".csv $model
