#!/bin/bash


RES_DIR=$PWD/../resource/ # beware! '/' at the end is required!
BUILD_DIR=$PWD/../bin/
model=$1
req=100
batch=4
mean=100
res=20

a=2

nvidia-smi dmon -d 1 -f data/dmon_"$model"_c"$a" &
smi_pid=$!

sleep 1

if true
then
nsys profile -t cuda -s none --export=sqlite --force-overwrite=true -o data/2060s_"$model"_t20_c$a ./conperf $a $model  
    
fi

python3 sepper.py data/2060s_"$model"_t20_c$a.sqlite $model $a

sleep 1
kill $smi_pid
sleep 1
python3 nvidiadmonps.py data/dmon_"$model"_c"$a" $model

#nsys profile -t cuda -s none --export=sqlite --force-overwrite=true -o data/v100_alexnet_t20_c$a ./conperf 2 alexnet
