#!/bin/bash

RES_DIR=$PWD/../resource/ # beware! '/' at the end is required!
BUILD_DIR=$PWD/../bin/
model=$1
req=100
batch=4
mean=100
res=20


#for i in {1,2,4,8,16,32}
#do

SERVER_PID=$(echo get_server_list | nvidia-cuda-mps-control)
echo set_active_thread_percentage $SERVER_PID $res | nvidia-cuda-mps-control
sleep 1


#kernels=$2
#echo set_active_thread_percentage $mpsid 20 | nvidia-cuda-mps-control
a=1   #1 biaoshi soloinference

if true
then
nsys profile -t cuda -s none --export=sqlite --force-overwrite=true -o data/2060s_"$model"_t20_c$a \
    $BUILD_DIR/standalone_inference --task $model --taskfile $RES_DIR/models/$model.pt --requests $req \
    --batch $batch --mean $mean --input $RES_DIR/$input_tx --input_config_json $RES_DIR/input_config.json
fi

python3 sepper.py data/2060s_"$model"_t20_c$a.sqlite $model 1
python3 transferdata.py data/2060s_"$model"_t20_c$a.sqlite $model
